name: Documentation
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit

      - name: Generate documentation
        run: npm run doc

      - name: Publish documentation
        run: npm run publish-docs
